### ISSUE TITLE
Why this plugin is not listed in the Wordpress plugin repository?

### ISSUE THREAD

**Issue by FutureMedia** [crowdfavorite/wp-post-formats#28]
Just said it.

**Comment by alexkingorg** [comment]
Because it isn't useful if not integrated into a theme.

**Comment by ayublin** [comment]
Hi @alexkingorg, thanks for the awesome plugin!

Can you please reconsider submitting the plugin to WordPress.org? This is useful for developers wanting to use this plugin in their theme and yet make it easier for the users to update the plugin them self. So that one can develop a theme requiring this plugin using a tool like https://github.com/thomasgriffin/TGM-Plugin-Activation. What do you think?

Best Regards,
Ayub Lin

**Comment by alexkingorg** [comment]
This is a code library - include it directly in your theme.

**Comment by ayublin** [comment]
Alright, thanks for the reply!
